### ISSUE TITLE
File names should be all lower case

### ISSUE THREAD

**Issue by rahmonov** [AlexBHarley/deepstream.py#3]
hey Alex, how is it going? I think that more pythonic way of naming files would be to use lower case letters. and do you need help with this?

**Comment by AlexBHarley** [comment]
hey @rahmonov, I have been working on the [java sdk](https://github.com/deepstreamIO/deepstream.io-client-java) lately, so this one has taken a bit of a back seat.

The python sdk is currently very limited in functionality (events and auth work maybe? no records or rpc) and tests. The tcp connection is also very suspect at the moment. 

If you want to make some contributions, that'd be great!

**Comment by rahmonov** [comment]
yeah, I would love to contribute! I think I should get to know Deepstream better before starting!

Were you familiar with Deepstream before starting to contribute? How did you get started?

**Comment by AlexBHarley** [comment]
@rahmonov this client is how I got a bit familiar. Didn't know anything before that. I did follow the same [Getting started](https://deepstream.io/tutorials/getting-started.html) tutorial that I saw you did.

I'd say, have a look at the different clients.
- [deepstream.io-client-js](https://github.com/deepstreamIO/deepstream.io-client-js) fully feature complete, maintained by the deepstream team
- [deepstream.io-client-java](https://github.com/deepstreamIO/deepstream.io-client-java) currently being worked on by myself and Yasser
- [deepstreamNet](https://github.com/schulz3000/deepstreamNet) a lot of work done
- [deepstream.py](https://github.com/AlexBHarley/deepstream.py) not as much work done.

If you want a quick win, the deepstreamNet client doesn't support the new [CONNECTION](https://deepstream.io/info/messagestructure/connectivity.html) messages, ie. C|A+, C|CH+ etc. Have a look at the other clients for examples of that.

If you want to write your own client, or contribute, maybe get a bit familiar with [this](https://deepstream.io/info/messagestructure/writing-a-client.html).

Other than that, there are a few [msg](https://github.com/deepstreamIO?utf8=%E2%9C%93&query=msg), [cache](https://github.com/deepstreamIO?utf8=%E2%9C%93&query=cache) and [storage](https://github.com/deepstreamIO?utf8=%E2%9C%93&query=storage) connectors you can look at if you want to write one of those. 

More info on that here:
- [Writing storage and cache connectors](https://deepstream.io/tutorials/writing-storage-cache-connector.html)
- [Writing a messaging connector](https://deepstream.io/tutorials/writing-messaging-connector.html)

I'm not an expert by any means but let me know if you have any questions

**Comment by rahmonov** [comment]
okay, got it! Thanks
